version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"